#include "appPython.h"

#if PEEL_HAS_PYTHON

#include "bindings.h"
#include "embeddedPython.h"

#include <QCoreApplication>
#include <QDir>
#include <QPointer>

#pragma push_macro("slots")
#undef slots
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#pragma pop_macro("slots")

// Generated by shiboken6 into this exe (peel_add_python_bindings).
extern "C" PyObject *PyInit_pfvgui();

namespace {

QPointer<MainWindow> g_mainWindow;

QString fromUtf8(const std::string &s)
{
    return QString::fromUtf8(s.data(), qsizetype(s.size()));
}

// The generated module calls into the shiboken6/pyside6 DLLs, which are
// delay-loaded from site-packages: importing PySide6 loads them first.
PyObject *initPfvgui()
{
    PyObject *pyside = PyImport_ImportModule("PySide6");
    if (!pyside)
        return nullptr;
    Py_DECREF(pyside);
    return PyInit_pfvgui();
}

} // namespace

MainWindow *mainWindow()
{
    return g_mainWindow.data();
}

bool appPythonStart(MainWindow *window, QString *error)
{
    g_mainWindow = window;
    PyImport_AppendInittab("pfvgui", &initPfvgui);

    const auto config = peel::pythonDefaultConfig(
        QDir::toNativeSeparators(QCoreApplication::applicationDirPath()).toStdWString());
    std::string err;
    if (!peel::pythonInit(config, &err) || !peel::pythonCall("pfv_startup", "install", nullptr, &err)) {
        *error = fromUtf8(err);
        return false;
    }
    return true;
}

bool appPythonCheck(QString *report)
{
    std::string result, err;
    const bool ok = peel::pythonCall("pfv_startup", "check", &result, &err);
    *report = fromUtf8(ok ? result : err);
    return ok;
}

void appPythonStop()
{
    peel::pythonFinalize();
}

#endif
