#pragma once

#include "peel_app_info.h"

#if PEEL_HAS_PYTHON

#include <QString>

class MainWindow;

// Starts the embedded interpreter with the built-in "pfvgui" module
// (generated by shiboken6 from src/bindings.h), then runs
// fileversions/pfv_startup.py's install(). Returns false with a message (a
// traceback for Python errors).
bool appPythonStart(MainWindow *window, QString *error);

// pfv_startup.check(): a report of what's loaded, for --python-check.
bool appPythonCheck(QString *report);

// Call after the main window is deleted (see peel::pythonFinalize()).
void appPythonStop();

#endif
